### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by IhostVlad** [risc0/tbb-sys#3]
Crates.io page https://docs.rs/tbb-sys/1.1.0+2021.5.0/tbb_sys/ and docs.rs page https://crates.io/crates/tbb-sys does not contain usage information
More than that, package seems to be autogenerated, so it's does not clear how to use it
Can you elaborate with small example with importing this library and, for example, invoking paraller_for ?

**Comment by flaub** [comment]
This is a wrapper for getting the Intel Threading Building Blocks building in the cargo build system. It's not meant to be used directly and is only used from C++ code. The oneTBB repository is a submodule so it's not actually autogenerated.

See: https://github.com/oneapi-src/oneTBB

**Comment by flaub** [comment]
Currently all uses of TBB happen here: https://github.com/risc0/risc0/blob/main/risc0/zkp/accel/backend/cpu/impl.cpp

**Comment by IhostVlad** [comment]
I initially thought that this crate-library is the Rust wrapper over the original C++ TBB library. I wonder if there is already a ready implemented cargo crate for rust with TBB safe wrappings?
If this is not the case, I thought at my leisure to do porting as much as I have free time. The combination of the power of TBB and the security and low-level nature of Rust looks very attractive :)
